# automatically fetch contract sources from Etherscan
autofetch_sources: true

networks:
  development:
    gas_price: 0
    cmd_settings:
      unlock: 0x7E1E3334130355799F833ffec2D731BCa3E68aF6

compiler:
    solc:
        optimizer:
            enabled: true
            runs: 1000000

dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.0.1

reports:
    exclude_contracts:
        - SafeMath
